purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.9575725
  brandStrength: 1
  lightness: 0.6170784
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#e2e2e2'
    - '#ababab'
    - '#5d5d5d'
  rhythmicContrast: 0.5
cta:
  bucket: null
  version: null
  domain: null
name: SignalBlack
favicon: null
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.339957
layout_spectrum: 1
